//! The Material colour pipeline, ported from materialyoucolor.
//!
//! The shell's palettes are generated by that Python library today, and the
//! only maintained Rust port of Material Color Utilities is a spec behind it
//! — measured against the palettes on this machine, dozens of colours come
//! out different. So this is a port of the library itself, checked against
//! reference vectors taken from it.

pub mod blend;
pub mod cam16;
pub mod colour;
pub mod contrast;
pub mod dislike;
pub mod hct;
pub mod math;
pub mod solver;
pub mod tables;
pub mod viewing;
